/*
 * CentralizedServer.java
 *
 * Created on September 15, 2008, 12:55 PM
 */
import javax.swing.*;
import java.io.*;
import java.awt.*;
import java.sql.*;
import java.net.*;

/**
 *
 * @author  Admin
 */
public class CentralizedServer extends javax.swing.JFrame {

	//ServerSocket ss2;
	ServerSocket ss3;
	Socket s2,s3;
    Socket s4,s6;
    Socket s5;
	Socket s7;
	Socket s8;
    Jdbc d = new Jdbc();
    int Count = 1;
    String[] send;
	String[] send1;
	String[] send2;

	/*String[] pdd0;
	String[] pdd1;
	String[] pdd2;*/

	String portno;	
	String direction;	
	String distance;	
	String location;	
	String criteria;

	ResultSet rs;
    /** Creates new form CentralizedServer */
    public CentralizedServer() {
        initComponents();
		setVisible(true);
		setSize(1200,1000);
		try {
            
               //ss2 = new ServerSocket(7777);     
               ss3 = new ServerSocket(6666);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        //jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        //jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18)); // NOI18N
        jLabel1.setText("Centralized Server");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 30, 190, 30);

        /*jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton1.setText("Save MH Details");
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 140, 140, 30);
		 jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });*/

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton2.setText("Process Query");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 140, 140, 30);
		 jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton3.setText("View MH_DB");
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 200, 140, 30);
		 jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton4.setText("View Query_DB");
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 260, 140, 30);
		 jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 140, 160, 210);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 140, 160, 210);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel2.setText("DB_Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 90, 120, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel3.setText("Server Info");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 90, 120, 30);

        /*jButton5.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton5.setText("Search Nearest Neighbour");
        getContentPane().add(jButton5);
        jButton5.setBounds(770, 140, 210, 30);
		 jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });*/

        jButton6.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton6.setText("Search Nearest Neighbour");
        getContentPane().add(jButton6);
        jButton6.setBounds(770, 140, 210, 30);
		 jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 402, 1200, 10);

        jButton7.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton7.setText("Response To MH");
        getContentPane().add(jButton7);
        jButton7.setBounds(770, 200, 150, 30);
		 jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton8.setText("Server Process");
        getContentPane().add(jButton8);
        jButton8.setBounds(770, 250, 150, 30);
		 jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18)); // NOI18N
        jLabel4.setText("Server DB Storage");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 430, 190, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel5.setText("PortNumber");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 500, 150, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel6.setText("Query Loc");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 560, 130, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel7.setText("Criteria");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 620, 140, 20);

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel8.setText("Query Results");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 680, 140, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(530, 500, 110, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(530, 560, 110, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(530, 620, 110, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(530, 680, 110, 30);

        jButton9.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton9.setText("Save");
        getContentPane().add(jButton9);
        jButton9.setBounds(300, 750, 67, 25);
		 jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton10.setText("Clear");
        getContentPane().add(jButton10);
        jButton10.setBounds(430, 750, 67, 25);
		 jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jButton11.setText("Exit");
        getContentPane().add(jButton11);
        jButton11.setBounds(570, 750, 67, 25);
		 jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/*private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
  try {
                    s2 = ss2.accept();
                    DataInputStream dis = new DataInputStream(s2.getInputStream());
                    String dd1 = dis.readUTF();
                    String[] pdd= dd1.split("&");
                    jTextArea1.append("Mobile User Details :"+"\n");
                    for (int i = 0; i < pdd.length; i++) 
						{
							String string = pdd[i]; 
							//System.out.println("Total values: "+string);           
						}                 
					d.insertServer("insert into DD_Details(Portno,Direction,Distance) values('"+pdd[0]+"','"+pdd[1]+"','"+pdd[2]+"')");
                    jTextArea1.append(Count+"."+"Port Number : "+pdd[0]+"\n");
					portno=pdd[0];
					direction=pdd[1];
                    distance=pdd[2];
					jTextArea1.append("Direction : "+pdd[1]+"\n");
                    jTextArea1.append("Distance : "+pdd[2]+"\n");
                    Count++;

        } catch (Exception e) {
            e.printStackTrace();
        }  
}*/

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
  try {
				s3 = ss3.accept();
				DataInputStream dis = new DataInputStream(s3.getInputStream());
				String dd11= dis.readUTF();
				send = dd11.split("&");
				jTextArea2.append("Query Details :"+"\n");   
				for (int i = 0; i < send.length; i++)
						{
							String string = send[i];  
						}
                //System.out.println(send[0]+""+send[1]+""+send[2]);
				d.insertServer("insert into Requested_Hosts values('"+send[0]+"','"+send[1]+"','"+send[2]+"')");
				jTextArea2.append(Count+"."+"Port Number :"+send[0]+"\n");
				location=send[1];
				criteria=send[2];
				jTextArea2.append("Location : "+send[1]+"\n");
				jTextArea2.append("Criteria : "+send[2]+"\n");
				Count++;
        
		} catch (Exception e) {
		  e.printStackTrace();
			}
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
 try {
               
               jTextArea1.append("MH Details: "+"\n"+"Portno                Direction                Distance "+"\n");
               String ss = d.retrive("select * from DD_Details");
               String cols[] = ss.split("&");              
               for (int i = 0; i < cols.length; i++)
				   {
						String string = cols[i];
						String[] MH = string.split("%");
						for (int j = 0; j < MH.length; j++) 
							{
									String string1 = MH[j];
									jTextArea1.append(string1+"\t");
							}
					  jTextArea1.append("\n");				
               
				}
              
            } catch (Exception e) {
				e.printStackTrace();
    } 
}

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
  try {
               jTextArea1.append("Query With Results : "+"\n"+"Portno                 Location               Criteria               Results "+"\n");
               String ss1 = d.retriveResults("select * from Query_Results");
               String cols1[] = ss1.split("&");               
               for (int i = 0; i < cols1.length; i++) 
				    {
							String string1 = cols1[i];
							String[] QR = string1.split("%");
							for (int j = 0; j < QR.length; j++) 
								{
										String string2 = QR[j];
										jTextArea1.append(string2+"\t");
								}
                        jTextArea1.append("\n");       
				    }
               
            } catch (Exception e) {
				e.printStackTrace();
			} 
}

/*private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:

System.out.println("Your PortNo :\t"+portno);
System.out.println("Your Direction :\t"+direction);
System.out.println("Your Distance :\t"+distance);
System.out.println("Your Location :\t"+location);
System.out.println("Your Criteria :\t"+criteria);

if(direction.equals("North"))
	{
	//check with NorthEast and NorthWest
	int distancemeasure=0;
	/*distance 
	for (distancemeasure=distance;distancemeasure<100 ;distancemeasure++ )
		{
			//for km distance
		}
	}
if(direction.equals("NorthEast"))
	{
	//check with North and East+
	}
  if(direction.equals("NorthWest"))
	{
	//check with North and West and consider distance
	}

if(direction.equals("East"))
	{
	//check with EastNorth and EastWest
	}



}*/

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
	String s0 = send[0];
    String s1 = send[1];
    String s2 = send[2];
	JOptionPane.showMessageDialog(this,s0);
	JOptionPane.showMessageDialog(this,s1);
	JOptionPane.showMessageDialog(this,s2);

	double servertime = System.currentTimeMillis();
	System.out.println("Server Time : "+servertime+" ms");

   try {
			if(s0.equals("1111"))
				{
						int PortNo =  d.retrivePort("select Portno from Query_Results where Location='"+send[1]+"'and Criteria='"+send[2]+"'");
						System.out.println("Port Number: "+PortNo);
						s5 = new Socket("localhost",4444); 
						DataOutputStream doutport = new DataOutputStream(s5.getOutputStream());
						doutport.writeInt(PortNo);
        		}
		else if(s0.equals("2222"))
				{
						int PortNo =  d.retrivePort("select Portno from Query_Results where Location='"+send[1]+"'and Criteria='"+send[2]+"'");
						System.out.println("Port Number: "+PortNo);
						s5 = new Socket("localhost",4445); 
						DataOutputStream doutport = new DataOutputStream(s5.getOutputStream());
						doutport.writeInt(PortNo);
				}
		else if(s0.equals("3333"))
				{
						int PortNo =  d.retrivePort("select Portno from Query_Results where Location='"+send[1]+"'and Criteria='"+send[2]+"'");
						System.out.println("Port Number: "+PortNo);
						s5 = new Socket("localhost",4446); 
						DataOutputStream doutport = new DataOutputStream(s5.getOutputStream());
						doutport.writeInt(PortNo);
        
				} 
		}catch (Exception e) {
				e.printStackTrace();
			}

	}

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
  
}

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
String ser0 = send[0];
String ser1 = send[1];
String ser2 = send[2];
System.out.println("ser val "+ser0+" "+ser1+" "+ser2);

try
{
	if(ser0.equals("1111"))
	{
		String fromServer = d.gettingResults("select Results from Query_Results where Location = '"+ser1+"' and Criteria = '"+ser2+"' ");
		DataOutputStream dosser = new DataOutputStream(s3.getOutputStream());
		dosser.writeUTF(fromServer);

	}else if(ser0.equals("2222"))
	{
		String fromServer = d.gettingResults("select Results from Query_Results where Location = '"+ser1+"' and Criteria = '"+ser2+"' ");
		DataOutputStream dosser = new DataOutputStream(s3.getOutputStream());
		dosser.writeUTF(fromServer);

	}else if(ser0.equals("3333"))
	{
		String fromServer = d.gettingResults("select Results from Query_Results where Location = '"+ser1+"' and Criteria = '"+ser2+"' ");
		DataOutputStream dosser = new DataOutputStream(s3.getOutputStream());
		dosser.writeUTF(fromServer);
	}
	}
	catch (Exception er)
	{
	er.printStackTrace();
	}

}

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
	String pno = jTextField1.getText();
    String qlc = jTextField2.getText();
    String cri = jTextField3.getText();
    String rst = jTextField4.getText();
    
    if(pno.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Enter Port Number");
    }
    else if(qlc.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Enter Query Location");
    }
    else if(cri.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Enter criteria");
    }
    else if(rst.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Enter Results");
    }
    else if(jButton6!=null)
    {
        String bu6mess = "Do You Want Save in Database?";
        
        int b4 =  JOptionPane.showConfirmDialog(this, bu6mess);
       if(b4==0)
       {
           try {
                    d.insertServer("insert into Query_Results values('"+pno+"','"+qlc+"','"+cri+"','"+rst+"')");
            
                } catch (Exception e) {
                  e.printStackTrace();
    }
          
       } 
    }
}

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
   jTextField1.setText("");
   jTextField2.setText("");
   jTextField3.setText("");
   jTextField4.setText("");
}

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
 
System.exit(0);
}


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       
                new CentralizedServer();
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
