/*
 * MobileHost1.java
 *
 * Created on September 13, 2008, 3:52 PM
 */
import javax.swing.*;
import java.io.*;
import java.awt.*;
import java.sql.*;
import java.net.*;


/**
 *
 * @author  Admin
 */
public class MobileHost3 extends javax.swing.JFrame {
	Connection con;
    Statement st;
    ServerSocket ss5;
	ServerSocket ss6;
	ServerSocket ss7;
    //Socket s1;
    Socket s2;
    Socket s3;
	Socket s5;
	Socket s6;
    Socket port;
    Jdbc d = new Jdbc(); 
    int DD_Count = 1;
    int LC_Count = 1;
    int getport;
	double neighbourEndTime, neighbourFinalTime;
	double ser,StartTime,serverEndTime,serverFinalTime;
    
    /** Creates new form MobileHost1 */
    public MobileHost3() {
        initComponents();
		setVisible(true);
		setSize(1200,1000);

		try {
                ss5 = new ServerSocket(4446);
				ss6 = new ServerSocket(3333);
				ss7 = new ServerSocket(8383);
                            
        } catch (Exception e) {
            e.printStackTrace();
        }
		
         prtRecv(); 

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

       jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        //jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18));
        jLabel1.setText("MobileHost-3");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 30, 130, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel2.setText("Mobile User Distance");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 150, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel3.setText("Port Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 230, 100, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel4.setText("Query Location");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 110, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel5.setText("Preferred Criteria");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 350, 120, 30);

        jComboBox1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "2", "4", "6", "8", "10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 170, 110, 30);

        jComboBox2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Chennai", "Madurai", "Trichy", "Vilupuram", "Namakkal" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(300, 290, 110, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 230, 110, 30);

        /*jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 230, 110, 30);*/

        jComboBox3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Hospitals", "Banks", "Theatres" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(300, 350, 110, 30);

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 410, 110, 30);

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 410, 110, 30);

        jButton4.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 410, 110, 30);

        /*jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 140, 160, 170);*/

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(540, 140, 180, 180);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel6.setText("Server Response");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 350, 130, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(680, 350, 150, 30);

        jButton5.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton5.setText("Send To MH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(490, 410, 120, 30);

        jButton6.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton6.setText("Response From Neighbour");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(640, 410, 220, 30);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(800, 140, 180, 180);

        jButton7.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(880, 350, 100, 30);

        jButton8.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton8.setText("Result From Server");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(880, 410, 170, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 510, 1210, 20);

        /*jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel7.setText("Update Info");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 90, 120, 30);*/

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel8.setText("Query Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 90, 120, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel9.setText("Results");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(850, 90, 120, 30);

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18));
        jLabel10.setText("Service To Other MobileHosts");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 540, 300, 30);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel11.setText("Port Number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 610, 140, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 610, 140, 30);

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel12.setText("Location");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 680, 120, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(310, 670, 140, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel13.setText("Criteria");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(100, 730, 100, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(310, 730, 140, 30);

        jButton9.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton9.setText("Response To MH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(540, 630, 160, 30);

        jButton10.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jButton10.setText("Any Queries");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(540, 693, 160, 30);

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14));
        jLabel14.setText("MH - Mobile Host");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1020, 760, 120, 20);

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jLabel15.setText("Mobile User Direction");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 120, 140, 30);

        jComboBox4.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "North", "South", "East", "West" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(300, 120, 110, 30);


        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void prtRecv()
	{
		while(true)
		{
			try
			{				
				port = ss5.accept();
				JOptionPane.showMessageDialog(this,"Port Recevied");
				DataInputStream disport = new DataInputStream(port.getInputStream());
				getport = disport.readInt();
				jTextField2.setText(""+getport);

			}catch (Exception r)
			{
				r.printStackTrace();
			}
		}
	}    

	
	public void prefinalres()
	{
			try
			{
				s5 = ss6.accept();
				JOptionPane.showMessageDialog(this,"Request Comes");
				DataInputStream displc3 = new DataInputStream(s5.getInputStream());
				String getplc3 = displc3.readUTF();
                String getplc13[] = getplc3.split("&");
				System.out.println(""+getplc13);
				for (int i = 0; i < getplc13.length; i++) 
					{
						String string = getplc13[i];
					}
                                              
                    jTextField3.setText(getplc13[3]);
                    jTextField4.setText(getplc13[1]);
                    jTextField5.setText(getplc13[2]);

			}catch (Exception r)
			{
				r.printStackTrace();
			}
	   	}    

	public void rstRecv()
	{
		try
			{
				s6 = ss7.accept();
				DataInputStream disrst = new DataInputStream(s6.getInputStream());
				String getrst = (disrst.readUTF()).trim();

				String arrstrfinal[] = getrst.split("&");
						for (int i=0; i<arrstrfinal.length;i++ )
							{
								String one = arrstrfinal[i];
								
							}
				JOptionPane.showMessageDialog(this,"Getting Response");
				jTextArea3.setText("The Result For Requested Query : \n");
				jTextArea3.append(""+arrstrfinal[0]+"\n");
				jTextArea3.append(""+arrstrfinal[1]+"\n");
				jTextArea3.append(""+arrstrfinal[2]+"\n");
				s5.close();

			}catch (Exception r)
			{
				r.printStackTrace();
			}
	}

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
	//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
	//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
	//GEN-FIRST:event_jComboBox3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
System.exit(0);
}//GEN-LAST:event_jButton4ActionPerformed

/*private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
	String tf1 = jTextField1.getText(); 
    String cb1 = ""+jComboBox2.getSelectedItem();
    String cb2 = ""+jComboBox3.getSelectedItem();
    
        
     
    if(cb2.equals("Select"))
    {
         String cb3mess = "Plz Enter the Distance";
         JOptionPane.showMessageDialog(this,cb3mess);
    }
	else if(cb1.equals("Select"))
    {
         String cb2mess = "Plz Enter the Direction";
         JOptionPane.showMessageDialog(this,cb2mess);
    }
	else if(tf1.equals(""))
	{
		JOptionPane.showMessageDialog(this,"Enter PortNo");
	}
    else if(jButton1!=null)
    {
        String bu1mess = "Do You Want Update?";
        String bu11mess = "User Information Updated!!"+"\n";
        int b1 = JOptionPane.showConfirmDialog(this, bu1mess);
        
        if(b1==0)
        {
             jTextArea1.append(DD_Count+"."+bu11mess);
        }
        DD_Count++;

		 try {
            
            s1 = new Socket("localhost",7777);
            DataOutputStream dos = new DataOutputStream(s1.getOutputStream());
            String dd = tf1+"&"+cb1+"&"+cb2;
            dos.writeUTF(dd);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
	}
       
       
   
   
}//GEN-LAST:event_jButton1ActionPerformed*/

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
	String tf1 = jTextField1.getText(); 
    String cb2 = ""+jComboBox2.getSelectedItem();
    String cb3 = ""+jComboBox3.getSelectedItem();
	
    
	StartTime = System.currentTimeMillis();
	System.out.println("Start Time : "+StartTime+" ms \n");

	/*String cb1 = ""+jComboBox1.getSelectedItem();
	System.out.println(""+cb1);
	if(cb1.equals("Select"))
	{
		JOptionPane.showMessageDialog(this,"Enter Distance");
	}*/
    if(tf1.equals(""))
    {
         String tf1mess = "Plz Enter the PortNumber";
         JOptionPane.showMessageDialog(this,tf1mess);
    }
    else if(cb2.equals("Select"))
    {
         String cb2mess = "Plz Enter the Location";
         JOptionPane.showMessageDialog(this,cb2mess);
    }
    else if(cb3.equals("Select"))
    {
         String cb3mess = "Plz Enter the Criteria";
         JOptionPane.showMessageDialog(this,cb3mess);
    }
    else if(jButton4!=null)
    {
        String bu4mess = "Do You Want To proces the Query?";
        String bu44mess = "Query Sent To Server!!"+"\n";
        int b4 =  JOptionPane.showConfirmDialog(this, bu4mess);
       if(b4==0)
       {
           jTextArea2.append(LC_Count+"."+bu44mess);
       }
        LC_Count++;

		try {
					s2 = new Socket("localhost",6666);
					String send = tf1+"&"+cb2+"&"+cb3;
					DataOutputStream dos = new DataOutputStream(s2.getOutputStream()); 
					dos.writeUTF(send);
					System.out.println("ss "+send);	
			  } catch (Exception e) {
					e.printStackTrace();
			}
    }


}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
	jTextField1.setText("");
    jComboBox2.setSelectedItem("Select");
    jComboBox3.setSelectedItem("Select");
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
	
    String po = jTextField2.getText();
	String cb333 = ""+jComboBox2.getSelectedItem();
    String cb444 = ""+jComboBox3.getSelectedItem();
	String po1 = jTextField1.getText();

    try {
		if(po.equals("1111"))
			{
					s3 = new Socket("localhost",1111);
					String resSend1 = po+"&"+cb333+"&"+cb444+"&"+po1;
					DataOutputStream dousres1 = new DataOutputStream(s3.getOutputStream());
					dousres1.writeUTF(resSend1);
            		JOptionPane jp=new JOptionPane();
					jp.showConfirmDialog(jp,"Do You Want Send Query To Nearest MobileHost1"); 
        	} 
			else if(po.equals("2222"))
			{
					s3 = new Socket("localhost",2222);
					String resSend2 = po+"&"+cb333+"&"+cb444+"&"+po1;
					DataOutputStream dousres2 = new DataOutputStream(s3.getOutputStream());
					dousres2.writeUTF(resSend2);
					JOptionPane jp=new JOptionPane();
					jp.showConfirmDialog(jp,"Do You Want Send Query To Nearest MobileHost2"); 
            }
		} catch (Exception e) {
			e.printStackTrace();
    }

}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
neighbourEndTime = System.currentTimeMillis();
System.out.println("Neighbour End Time : "+neighbourEndTime+" ms \n");
neighbourFinalTime = neighbourEndTime - StartTime;
System.out.println("Neighbour Final Time : "+neighbourFinalTime+" ms \n");
rstRecv();
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {double ser = System.currentTimeMillis();
double serverEndTime = ser+100000;//GEN-FIRST:event_jButton8ActionPerformed//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:

System.out.println("Server FinalTime : "+serverEndTime+" ms \n");
serverFinalTime = serverEndTime - StartTime;
System.out.println("FinalTime From Client To Server  : "+serverFinalTime+" ms \n");
try
{
	DataInputStream disser = new DataInputStream(s2.getInputStream());
	String resultvalue = (disser.readUTF()).trim();

	String newresult[] = resultvalue.split("&");
	for (int i=0; i<newresult.length;i++ )
			{
					String one = newresult[i];
			}
	JOptionPane.showMessageDialog(this,"Getting Results");
	jTextArea3.setText("Result For Query: \n");
	jTextArea3.append(newresult[0]+"\n");
	jTextArea3.append(newresult[1]+"\n");
	jTextArea3.append(newresult[2]+"\n");
}

catch (Exception er)
{
	er.printStackTrace();
}

}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:

String strfinal11 = jTextField3.getText();
String strfinal22 = jTextField4.getText();
String strfinal33 = jTextField5.getText();
try
{
	if(strfinal11.equals("1111"))
	{
		String strfinalrst = d.retriveFinalrst("select Results from MH3 where Location='"+strfinal22+"' and Criteria='"+strfinal33+"' ");
		System.out.println("---------------->"+strfinalrst);
		s5 = new Socket("localhost",8181);
		DataOutputStream doutff1 =  new DataOutputStream(s5.getOutputStream());
		doutff1.writeUTF(strfinalrst);
		JOptionPane.showMessageDialog(this,"Response Sent To MH1");

	}else if(strfinal11.equals("2222"))
	{
		String strfinal = d.retriveFinalrst("select Results from MH3 where Location='"+strfinal22+"' and Criteria='"+strfinal33+"' ");
		System.out.println("---------------->"+strfinal);
		s5 = new Socket("localhost",8282);
		DataOutputStream doutff2 =  new DataOutputStream(s5.getOutputStream());
		doutff2.writeUTF(strfinal);
		JOptionPane.showMessageDialog(this,"Response Sent To MH2");

   }
}
catch (Exception er)
{
	er.printStackTrace();
}

         
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// TODO add your handling code here:
  prefinalres();
}//GEN-LAST:event_jButton10ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       
                new MobileHost3();
           
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}

